visual_parameters:
  base_link:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link0.obj
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link0.stl
    workspace:
      origin:
        x: 0
        y: 0
        z: 0.365
        roll: 0
        pitch: 0
        yaw: 0
      sphere:
        radius: 0.890
  link1:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link1.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.062 0.062 0.002
        origin:
          x: 0
          y: 0
          z: -0.0025
          roll: 0
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link1.stl
  link2:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link2.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.062 0.062 0.002
        origin:
          x: 0
          y: -0.0025
          z: 0
          roll: 1.5707963
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link2.stl
  link3:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link3.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.051 0.051 0.002
        origin:
          x: 0
          y: 0
          z: -0.0025
          roll: 0
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link3.stl
  link4:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link4.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.051 0.051 0.002
        origin:
          x: 0
          y: -0.0025
          z: 0
          roll: 1.5707963
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link4.stl
  link5:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link5.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.051 0.051 0.002
        origin:
          x: 0
          y: 0
          z: -0.0025
          roll: 0
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link5.stl
  link6:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link6.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.051 0.051 0.002
        origin:
          x: 0
          y: -0.0025
          z: 0
          roll: 1.5707963
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link6.stl
  link7:
    visual:
      shell:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/link7.obj
      ring:
        mesh:
          package: flexiv_description
          path: meshes/Rizon4s/visual/ring.obj
          scale: 0.051 0.051 0.002
        origin:
          x: 0
          y: 0
          z: -0.0025
          roll: 0
          pitch: 0
          yaw: 0
    collision:
      mesh:
        package: flexiv_description
        path: meshes/Rizon4s/collision/link7.stl
