joint_limits:
  joint1:
    lower: -2.8798
    upper: 2.8798
    effort: 261
    velocity: 1.7453
    soft_lower: -2.7925
    soft_upper: 2.7925
  joint2:
    lower: -2.7576
    upper: 2.7576
    effort: 261
    velocity: 1.7453
    soft_lower: -2.6704
    soft_upper: 2.6704
  joint3:
    lower: -2.8798
    upper: 2.8798
    effort: 123
    velocity: 2.0944
    soft_lower: -2.7925
    soft_upper: 2.7925
  joint4:
    lower: -2.7925
    upper: 2.7925
    effort: 123
    velocity: 2.0944
    soft_lower: -2.7053
    soft_upper: 2.7053
  joint5:
    lower: -3.0543
    upper: 3.0543
    effort: 57
    velocity: 3.8397
    soft_lower: -2.9671
    soft_upper: 2.9671
  joint6:
    lower: -1.4835
    upper: 4.6251
    effort: 57
    velocity: 3.8397
    soft_lower: -1.3963
    soft_upper: 4.5379
  joint7:
    lower: -3.0543
    upper: 3.0543
    effort: 57
    velocity: 3.8397
    soft_lower: -2.9671
    soft_upper: 2.9671
