inertia_parameters:
  wrist_sensor_base_link:
    mass: 1E-4
    origin:
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
    inertia:
      ixx: 1E-7
      ixy: 0
      ixz: 0
      iyy: 1E-7
      iyz: 0
      izz: 1E-7
  wrist_sensor_proximal_link:
    mass: 0.149
    origin:
      x: 0
      y: 0
      z: 0.01955
      roll: 0
      pitch: 0
      yaw: 0
    inertia:
      ixx: 8.6E-5
      ixy: 0
      ixz: 0
      iyy: 8.6E-5
      iyz: 0
      izz: 1E-7
  wrist_sensor_distal_link:
    mass: 0.249
    origin:
      x: 0
      y: 0
      z: 0.0085
      roll: 0
      pitch: 0
      yaw: 0
    inertia:
      ixx: 1.05E-4
      ixy: 0
      ixz: 0
      iyy: 1.05E-4
      iyz: -0
      izz: 1.81E-4
